---

- name: Create configuration directory
  file:
    path: "{{ cassandra_configuration_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0544

- name: Set Cassandra configuration files
  template:
    src: etc/cassandra/{{ cassandra_install_version }}/{{ item }}.j2
    dest: "{{ cassandra_configuration_directory }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - cassandra.in.sh
    - cassandra-env.sh
    - cassandra.yaml
    - logback.xml
    - logback-tools.xml
