---
- include: bootstrap.yml
  tags:
    - cassandra
    - bootstrap

- include: install.yml
  tags:
    - cassandra
    - install

- include: configure.yml
  tags:
    - cassandra
    - configure

- name: Start Cassandra service
  service:
    name: cassandra
    state: started
